name: Build(Debug)

on:
  push:
    branches: [ develop, release-*, hotfix-*, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: "Set flag from Commit"
      run: |
        if $GITHUB_REF_NAME == develop; then
          echo "cfg=Debug" >> $GITHUB_ENV
          echo "cfg set to Debug"
        else
          echo "cfg=Release" >> $GITHUB_ENV
          echo "cfg set to Release"
        fi
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build solution
      run: dotnet build --configuration ${{ env.cfg }} --no-restore --verbosity Normal --output BuildResults --disable-parallel